{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes, job)"
   },
   {
    "name": "instance",
    "query": "label_values(process_resident_memory_bytes, instance)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Limit Percentage",
   "type": "graph",
   "description": "Current CPU usage to Pod memory resource limit in percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instanc=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, job) (go_goroutines{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,job) (process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}} - resident"
    },
    {
     "expr": "avg by (instance,job) (process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}} - virtual"
    }
   ]
  },
  {
   "title": "Process Memory Derivative",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, job) (deriv(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}} - resident"
    },
    {
     "expr": "avg by (instance, job) (deriv(process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}} - virtual"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (go_memstats_alloc_bytes{job=~\"open-match\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "avg by (instance, job) (rate(go_memstats_alloc_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}} - alloc rate"
    },
    {
     "expr": "avg by (instance, job) (go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}} - stack inuse"
    },
    {
     "expr": "avg by (instance, job) (go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go Memstats Derivative",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, job) (deriv(go_memstats_alloc_bytes{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}} - bytes allocated"
    },
    {
     "expr": "avg by (instance, job) (deriv(go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}} - stack inuse"
    },
    {
     "expr": "avg by (instance, job) (deriv(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, job) (process_open_fds{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors Derivative",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, job) (deriv(process_open_fds{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (instance, quantile, job) (go_gc_duration_seconds{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}} - {{instance}}: {{quantile}}"
    }
   ]
  }
 ]
}