version: '3.7'

services:
  om-prometheus:
    image: 172.16.1.13:5000/gv-ns-studio/openmatch-prometheus:1.1.0
    networks:
      - om-back
      - om-front
    ports:
      - 9191:9090
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  om-redis-exporter:
    image: docker.io/bitnami/redis-exporter:1.3.1-debian-9-r9
    environment:
      - REDIS_ADDR=om-redis
    networks:
      - om-back
    ports:
      - 9121:9121
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  om-grafana:
    image: 172.16.1.13:5000/gv-ns-studio/openmatch-grafana:1.1.0
    networks:
      - om-back
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
