// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/evaluator.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EvaluateRequest struct {
	// A Matches proposed by the Match Function representing a candidate of the final results.
	Match                *Match   `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvaluateRequest) Reset()         { *m = EvaluateRequest{} }
func (m *EvaluateRequest) String() string { return proto.CompactTextString(m) }
func (*EvaluateRequest) ProtoMessage()    {}
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c58cb7dff9acb0f, []int{0}
}

func (m *EvaluateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateRequest.Unmarshal(m, b)
}
func (m *EvaluateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateRequest.Marshal(b, m, deterministic)
}
func (m *EvaluateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateRequest.Merge(m, src)
}
func (m *EvaluateRequest) XXX_Size() int {
	return xxx_messageInfo_EvaluateRequest.Size(m)
}
func (m *EvaluateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateRequest proto.InternalMessageInfo

func (m *EvaluateRequest) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

type EvaluateResponse struct {
	// A Match ID representing a shortlisted match returned by the evaluator as the final result.
	MatchId              string   `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvaluateResponse) Reset()         { *m = EvaluateResponse{} }
func (m *EvaluateResponse) String() string { return proto.CompactTextString(m) }
func (*EvaluateResponse) ProtoMessage()    {}
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c58cb7dff9acb0f, []int{1}
}

func (m *EvaluateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateResponse.Unmarshal(m, b)
}
func (m *EvaluateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateResponse.Marshal(b, m, deterministic)
}
func (m *EvaluateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateResponse.Merge(m, src)
}
func (m *EvaluateResponse) XXX_Size() int {
	return xxx_messageInfo_EvaluateResponse.Size(m)
}
func (m *EvaluateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateResponse proto.InternalMessageInfo

func (m *EvaluateResponse) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func init() {
	proto.RegisterType((*EvaluateRequest)(nil), "openmatch.EvaluateRequest")
	proto.RegisterType((*EvaluateResponse)(nil), "openmatch.EvaluateResponse")
}

func init() { proto.RegisterFile("api/evaluator.proto", fileDescriptor_8c58cb7dff9acb0f) }

var fileDescriptor_8c58cb7dff9acb0f = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0xd2, 0x26, 0xcb, 0x81, 0x68, 0x41, 0x28, 0x04, 0x84, 0x96, 0x54, 0x42, 0x21,
	0x22, 0xde, 0x34, 0xcd, 0x85, 0x20, 0xa4, 0x16, 0xc8, 0x21, 0xa8, 0x80, 0x14, 0x24, 0x0e, 0x5c,
	0xd0, 0xda, 0x1e, 0x6c, 0x43, 0xbc, 0xb3, 0xec, 0xac, 0x53, 0x6e, 0x20, 0x3e, 0x01, 0x6e, 0x7c,
	0x02, 0x57, 0x3e, 0x85, 0x1b, 0x67, 0x3e, 0x04, 0xd9, 0x26, 0x24, 0xa2, 0xbd, 0xd8, 0xda, 0x7d,
	0x6f, 0xdf, 0x9b, 0x79, 0x33, 0xec, 0xb2, 0x32, 0x99, 0x84, 0x95, 0x5a, 0x16, 0xca, 0xa1, 0x0d,
	0x8c, 0x45, 0x87, 0xbc, 0x85, 0x06, 0x74, 0xae, 0x5c, 0x94, 0x76, 0x79, 0x89, 0xe7, 0x40, 0xa4,
	0x12, 0xa0, 0x1a, 0xee, 0xde, 0x48, 0x10, 0x93, 0x25, 0xc8, 0x12, 0x52, 0x5a, 0xa3, 0x53, 0x2e,
	0x43, 0xbd, 0x46, 0xef, 0x56, 0xbf, 0x68, 0x98, 0x80, 0x1e, 0xd2, 0xa9, 0x4a, 0x12, 0xb0, 0x12,
	0x4d, 0xc5, 0x38, 0xcb, 0xee, 0xdd, 0x63, 0x97, 0x66, 0xb5, 0x3b, 0x2c, 0xe0, 0x7d, 0x01, 0xe4,
	0xf8, 0x6d, 0x76, 0xa1, 0xf2, 0xee, 0x78, 0xc2, 0xeb, 0x5f, 0x1c, 0xb7, 0x83, 0x7f, 0xd5, 0x04,
	0x4f, 0xcb, 0xef, 0xa2, 0x86, 0x7b, 0x87, 0xac, 0xbd, 0x79, 0x4a, 0x06, 0x35, 0x01, 0xbf, 0xc6,
	0x9a, 0x15, 0xf8, 0x3a, 0x8b, 0x3b, 0xbe, 0xf0, 0xfa, 0xad, 0xc5, 0x5e, 0x75, 0x9e, 0xc7, 0x4f,
	0x76, 0x9a, 0x5e, 0xdb, 0x1f, 0x7f, 0x64, 0xad, 0xd9, 0xba, 0x5b, 0x6e, 0x59, 0x73, 0xad, 0xc0,
	0xbb, 0x5b, 0x36, 0xff, 0x55, 0xd4, 0xbd, 0x7e, 0x2e, 0x56, 0x5b, 0xf6, 0xee, 0x7c, 0xfe, 0xf9,
	0xfb, 0xab, 0xbf, 0xdf, 0xbb, 0x29, 0x57, 0x07, 0x9b, 0x24, 0x65, 0xc5, 0x06, 0x9a, 0xfe, 0xbd,
	0x81, 0xa9, 0x37, 0xe8, 0x7b, 0x23, 0xef, 0xe1, 0xa7, 0xc6, 0x97, 0xe3, 0x5f, 0x3e, 0xff, 0xe1,
	0x6d, 0x15, 0xd2, 0x9b, 0x33, 0xf6, 0xdc, 0x80, 0x16, 0x55, 0x7f, 0xfc, 0x6a, 0xea, 0x9c, 0xa1,
	0xa9, 0x94, 0xa5, 0xeb, 0xb0, 0xb6, 0x8d, 0x61, 0xd5, 0xdd, 0xdf, 0x9c, 0x87, 0x71, 0x46, 0x51,
	0x41, 0x74, 0x54, 0x8f, 0x22, 0xb1, 0x58, 0x18, 0x0a, 0x22, 0xcc, 0x07, 0x2f, 0x19, 0x3f, 0x36,
	0x2a, 0x4a, 0x41, 0x8c, 0x83, 0x91, 0x38, 0xc9, 0x22, 0x28, 0x73, 0x39, 0x5a, 0x4b, 0x26, 0x99,
	0x4b, 0x8b, 0xb0, 0x64, 0xca, 0xfa, 0xe9, 0x1b, 0xb4, 0x89, 0xca, 0x81, 0xb6, 0xcc, 0x64, 0xb8,
	0xc4, 0x50, 0xe6, 0x8a, 0x1c, 0x58, 0x79, 0x32, 0x7f, 0x34, 0x7b, 0xf6, 0x62, 0x36, 0x6e, 0x1c,
	0x04, 0xa3, 0x81, 0xef, 0xf9, 0xe3, 0xb6, 0x32, 0x66, 0x99, 0x45, 0xd5, 0x14, 0xe5, 0x5b, 0x42,
	0x3d, 0x3d, 0x73, 0xb3, 0xb8, 0xcf, 0x1a, 0x93, 0xd1, 0x84, 0x4f, 0xd8, 0x60, 0x01, 0xae, 0xb0,
	0x1a, 0x62, 0x71, 0x9a, 0x82, 0x16, 0x2e, 0x05, 0x61, 0x81, 0xb0, 0xb0, 0x11, 0x88, 0x18, 0x81,
	0x84, 0x46, 0x27, 0xe0, 0x43, 0x46, 0x2e, 0xe0, 0xbb, 0x6c, 0xe7, 0x9b, 0xef, 0xed, 0xd9, 0x07,
	0xac, 0xb3, 0x09, 0x43, 0x3c, 0xc6, 0xa8, 0xc8, 0x41, 0xd7, 0x5b, 0xc3, 0x6f, 0x9d, 0x1f, 0x8d,
	0xa4, 0xcc, 0x81, 0x8c, 0x31, 0x22, 0xf9, 0xea, 0x8a, 0xa6, 0xe1, 0x56, 0x2f, 0xe6, 0x5d, 0x22,
	0x4d, 0xf8, 0xdd, 0x6f, 0x95, 0x9a, 0x95, 0x64, 0xb8, 0x5b, 0xad, 0xde, 0xe1, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb9, 0xda, 0x08, 0xa7, 0xfc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EvaluatorClient is the client API for Evaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EvaluatorClient interface {
	// Evaluate evaluates a list of proposed matches based on quality, collision status, and etc, then shortlist the matches and returns the final results.
	Evaluate(ctx context.Context, opts ...grpc.CallOption) (Evaluator_EvaluateClient, error)
}

type evaluatorClient struct {
	cc *grpc.ClientConn
}

func NewEvaluatorClient(cc *grpc.ClientConn) EvaluatorClient {
	return &evaluatorClient{cc}
}

func (c *evaluatorClient) Evaluate(ctx context.Context, opts ...grpc.CallOption) (Evaluator_EvaluateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Evaluator_serviceDesc.Streams[0], "/openmatch.Evaluator/Evaluate", opts...)
	if err != nil {
		return nil, err
	}
	x := &evaluatorEvaluateClient{stream}
	return x, nil
}

type Evaluator_EvaluateClient interface {
	Send(*EvaluateRequest) error
	Recv() (*EvaluateResponse, error)
	grpc.ClientStream
}

type evaluatorEvaluateClient struct {
	grpc.ClientStream
}

func (x *evaluatorEvaluateClient) Send(m *EvaluateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *evaluatorEvaluateClient) Recv() (*EvaluateResponse, error) {
	m := new(EvaluateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EvaluatorServer is the server API for Evaluator service.
type EvaluatorServer interface {
	// Evaluate evaluates a list of proposed matches based on quality, collision status, and etc, then shortlist the matches and returns the final results.
	Evaluate(Evaluator_EvaluateServer) error
}

// UnimplementedEvaluatorServer can be embedded to have forward compatible implementations.
type UnimplementedEvaluatorServer struct {
}

func (*UnimplementedEvaluatorServer) Evaluate(srv Evaluator_EvaluateServer) error {
	return status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}

func RegisterEvaluatorServer(s *grpc.Server, srv EvaluatorServer) {
	s.RegisterService(&_Evaluator_serviceDesc, srv)
}

func _Evaluator_Evaluate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EvaluatorServer).Evaluate(&evaluatorEvaluateServer{stream})
}

type Evaluator_EvaluateServer interface {
	Send(*EvaluateResponse) error
	Recv() (*EvaluateRequest, error)
	grpc.ServerStream
}

type evaluatorEvaluateServer struct {
	grpc.ServerStream
}

func (x *evaluatorEvaluateServer) Send(m *EvaluateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *evaluatorEvaluateServer) Recv() (*EvaluateRequest, error) {
	m := new(EvaluateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Evaluator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openmatch.Evaluator",
	HandlerType: (*EvaluatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Evaluate",
			Handler:       _Evaluator_Evaluate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/evaluator.proto",
}
