// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/matchfunction.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunRequest struct {
	// A MatchProfile defines constraints of Tickets in a Match and shapes the Match proposed by the MatchFunction.
	Profile              *MatchProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b5069a21f149a55, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetProfile() *MatchProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type RunResponse struct {
	// A Proposal represents a Match candidate that satifies the constraints defined in the input Profile.
	// A valid Proposal response will contain at least one ticket.
	Proposal             *Match   `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b5069a21f149a55, []int{1}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetProposal() *Match {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "openmatch.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "openmatch.RunResponse")
}

func init() { proto.RegisterFile("api/matchfunction.proto", fileDescriptor_2b5069a21f149a55) }

var fileDescriptor_2b5069a21f149a55 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0xd5, 0x4c, 0x3e, 0xb5, 0x5f, 0x5d, 0x81, 0x2a, 0x8b, 0xfe, 0x28, 0x62, 0x61, 0xc2, 0x06,
	0x45, 0xcd, 0x38, 0x0d, 0x5d, 0xa5, 0x42, 0xb4, 0x40, 0x91, 0x2a, 0x95, 0x1f, 0x0d, 0x12, 0x42,
	0xec, 0x1c, 0xe7, 0x66, 0x66, 0x20, 0xf1, 0x35, 0xbe, 0x76, 0xcb, 0x1a, 0x89, 0x17, 0x80, 0x1d,
	0x8f, 0xc0, 0x13, 0xf0, 0x1e, 0x3c, 0x00, 0x1b, 0x1e, 0x04, 0x8d, 0xa7, 0x69, 0x42, 0xcb, 0x66,
	0x46, 0x3e, 0xe7, 0xdc, 0x73, 0xec, 0x63, 0xb3, 0x6d, 0x65, 0x2b, 0x39, 0x53, 0x5e, 0x97, 0x93,
	0x60, 0xb4, 0xaf, 0xd0, 0x64, 0xd6, 0xa1, 0x47, 0xbe, 0x86, 0x16, 0x4c, 0x24, 0xda, 0x3c, 0x6a,
	0x80, 0x48, 0x15, 0x40, 0x0d, 0xdd, 0xbe, 0x5d, 0x20, 0x16, 0x53, 0x90, 0x35, 0xa5, 0x8c, 0x41,
	0xaf, 0xea, 0xd9, 0x39, 0xbb, 0x1b, 0x7f, 0xba, 0x57, 0x80, 0xe9, 0xd1, 0xb9, 0x2a, 0x0a, 0x70,
	0x12, 0x6d, 0x54, 0x5c, 0x57, 0x77, 0x1e, 0x32, 0x96, 0x07, 0x93, 0xc3, 0x87, 0x00, 0xe4, 0xf9,
	0x1e, 0x5b, 0xb5, 0x0e, 0x27, 0xd5, 0x14, 0x76, 0x12, 0x91, 0xdc, 0x5b, 0x1f, 0x6c, 0x67, 0x97,
	0x5b, 0xc9, 0x9e, 0xd5, 0xdf, 0x97, 0x0d, 0x9d, 0xcf, 0x75, 0x9d, 0x03, 0xb6, 0x1e, 0x0d, 0xc8,
	0xa2, 0x21, 0xe0, 0xbb, 0xec, 0x7f, 0xeb, 0xd0, 0x22, 0xa9, 0xe9, 0x85, 0xc5, 0xc6, 0x55, 0x8b,
	0xfc, 0x52, 0x31, 0xa8, 0xd8, 0x8d, 0x08, 0x3d, 0xbd, 0x38, 0x3f, 0x7f, 0xc3, 0x5a, 0x79, 0x30,
	0x7c, 0x73, 0x69, 0x66, 0xb1, 0xbd, 0xf6, 0xd6, 0x55, 0xb8, 0x09, 0xed, 0x88, 0x4f, 0x3f, 0x7f,
	0x7f, 0x4d, 0xdb, 0x9d, 0x4d, 0x79, 0xb6, 0xf7, 0x77, 0xa1, 0x43, 0x17, 0xcc, 0x30, 0xe9, 0xf6,
	0x93, 0x47, 0x9f, 0x5b, 0x5f, 0x8e, 0x7e, 0xa5, 0xfc, 0x47, 0xc2, 0x6e, 0xc6, 0x48, 0x31, 0xcf,
	0xec, 0x9c, 0x30, 0xf6, 0xc2, 0x82, 0x11, 0x11, 0xe6, 0x5b, 0xa5, 0xf7, 0x96, 0x86, 0x52, 0xd6,
	0x51, 0xbd, 0x26, 0x6b, 0x0c, 0x67, 0xed, 0xbb, 0x8b, 0x75, 0x6f, 0x5c, 0x91, 0x0e, 0x44, 0x87,
	0xcd, 0x3d, 0x14, 0x0e, 0x83, 0xa5, 0x4c, 0xe3, 0xac, 0xfb, 0x9a, 0xf1, 0x23, 0xab, 0x74, 0x09,
	0x62, 0x90, 0xf5, 0xc5, 0x69, 0xa5, 0xa1, 0xee, 0xe4, 0x70, 0x6e, 0x59, 0x54, 0xbe, 0x0c, 0xa3,
	0x5a, 0x29, 0x9b, 0xd1, 0x09, 0xba, 0x42, 0xcd, 0x80, 0x96, 0xc2, 0xe4, 0x68, 0x8a, 0x23, 0x39,
	0x53, 0xe4, 0xc1, 0xc9, 0xd3, 0x93, 0xc7, 0xc7, 0xcf, 0x5f, 0x1d, 0x0f, 0x5a, 0x7b, 0x59, 0xbf,
	0x9b, 0x26, 0xe9, 0x60, 0x43, 0x59, 0x3b, 0xad, 0x74, 0xbc, 0x42, 0xf9, 0x8e, 0xd0, 0x0c, 0xaf,
	0x21, 0xf9, 0x01, 0x6b, 0xed, 0xf7, 0xf7, 0xf9, 0x3e, 0xeb, 0xe6, 0xe0, 0x83, 0x33, 0x30, 0x16,
	0xe7, 0x25, 0x18, 0xe1, 0x4b, 0x10, 0x0e, 0x08, 0x83, 0xd3, 0x20, 0xc6, 0x08, 0x24, 0x0c, 0x7a,
	0x01, 0x1f, 0x2b, 0xf2, 0x19, 0x5f, 0x61, 0xff, 0x7d, 0x4b, 0x93, 0x55, 0xf7, 0x80, 0xed, 0x2c,
	0xca, 0x10, 0x4f, 0x50, 0x87, 0x19, 0x98, 0xe6, 0xc9, 0xf0, 0x3b, 0xff, 0xae, 0x46, 0x52, 0xe5,
	0x41, 0x8e, 0x51, 0x93, 0x7c, 0x7b, 0xcb, 0x50, 0x6f, 0xe9, 0x2c, 0xf6, 0x7d, 0x21, 0xed, 0xe8,
	0x7b, 0xba, 0x56, 0x7b, 0x46, 0xcb, 0xd1, 0x4a, 0x7c, 0x77, 0xf7, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x28, 0x0b, 0x76, 0x94, 0xfd, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MatchFunctionClient is the client API for MatchFunction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MatchFunctionClient interface {
	// DO NOT CALL THIS FUNCTION MANUALLY. USE backend.FetchMatches INSTEAD.
	// Run pulls Tickets that satisfy Profile constraints from QueryService, runs matchmaking logics against them, then
	// constructs and streams back match candidates to the Backend service.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (MatchFunction_RunClient, error)
}

type matchFunctionClient struct {
	cc *grpc.ClientConn
}

func NewMatchFunctionClient(cc *grpc.ClientConn) MatchFunctionClient {
	return &matchFunctionClient{cc}
}

func (c *matchFunctionClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (MatchFunction_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MatchFunction_serviceDesc.Streams[0], "/openmatch.MatchFunction/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &matchFunctionRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MatchFunction_RunClient interface {
	Recv() (*RunResponse, error)
	grpc.ClientStream
}

type matchFunctionRunClient struct {
	grpc.ClientStream
}

func (x *matchFunctionRunClient) Recv() (*RunResponse, error) {
	m := new(RunResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MatchFunctionServer is the server API for MatchFunction service.
type MatchFunctionServer interface {
	// DO NOT CALL THIS FUNCTION MANUALLY. USE backend.FetchMatches INSTEAD.
	// Run pulls Tickets that satisfy Profile constraints from QueryService, runs matchmaking logics against them, then
	// constructs and streams back match candidates to the Backend service.
	Run(*RunRequest, MatchFunction_RunServer) error
}

// UnimplementedMatchFunctionServer can be embedded to have forward compatible implementations.
type UnimplementedMatchFunctionServer struct {
}

func (*UnimplementedMatchFunctionServer) Run(req *RunRequest, srv MatchFunction_RunServer) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterMatchFunctionServer(s *grpc.Server, srv MatchFunctionServer) {
	s.RegisterService(&_MatchFunction_serviceDesc, srv)
}

func _MatchFunction_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchFunctionServer).Run(m, &matchFunctionRunServer{stream})
}

type MatchFunction_RunServer interface {
	Send(*RunResponse) error
	grpc.ServerStream
}

type matchFunctionRunServer struct {
	grpc.ServerStream
}

func (x *matchFunctionRunServer) Send(m *RunResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MatchFunction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openmatch.MatchFunction",
	HandlerType: (*MatchFunctionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _MatchFunction_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/matchfunction.proto",
}
