// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/query.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryTicketsRequest struct {
	// The Pool representing the set of Filters to be queried.
	Pool                 *Pool    `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTicketsRequest) Reset()         { *m = QueryTicketsRequest{} }
func (m *QueryTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTicketsRequest) ProtoMessage()    {}
func (*QueryTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec7651f31a90698, []int{0}
}

func (m *QueryTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketsRequest.Unmarshal(m, b)
}
func (m *QueryTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketsRequest.Marshal(b, m, deterministic)
}
func (m *QueryTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketsRequest.Merge(m, src)
}
func (m *QueryTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTicketsRequest.Size(m)
}
func (m *QueryTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketsRequest proto.InternalMessageInfo

func (m *QueryTicketsRequest) GetPool() *Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type QueryTicketsResponse struct {
	// Tickets that meet all the filtering criteria requested by the pool.
	Tickets              []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryTicketsResponse) Reset()         { *m = QueryTicketsResponse{} }
func (m *QueryTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTicketsResponse) ProtoMessage()    {}
func (*QueryTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec7651f31a90698, []int{1}
}

func (m *QueryTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketsResponse.Unmarshal(m, b)
}
func (m *QueryTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketsResponse.Marshal(b, m, deterministic)
}
func (m *QueryTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketsResponse.Merge(m, src)
}
func (m *QueryTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTicketsResponse.Size(m)
}
func (m *QueryTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketsResponse proto.InternalMessageInfo

func (m *QueryTicketsResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type QueryTicketIdsRequest struct {
	// The Pool representing the set of Filters to be queried.
	Pool                 *Pool    `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTicketIdsRequest) Reset()         { *m = QueryTicketIdsRequest{} }
func (m *QueryTicketIdsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTicketIdsRequest) ProtoMessage()    {}
func (*QueryTicketIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec7651f31a90698, []int{2}
}

func (m *QueryTicketIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketIdsRequest.Unmarshal(m, b)
}
func (m *QueryTicketIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketIdsRequest.Marshal(b, m, deterministic)
}
func (m *QueryTicketIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketIdsRequest.Merge(m, src)
}
func (m *QueryTicketIdsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTicketIdsRequest.Size(m)
}
func (m *QueryTicketIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketIdsRequest proto.InternalMessageInfo

func (m *QueryTicketIdsRequest) GetPool() *Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type QueryTicketIdsResponse struct {
	// TicketIDs that meet all the filtering criteria requested by the pool.
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTicketIdsResponse) Reset()         { *m = QueryTicketIdsResponse{} }
func (m *QueryTicketIdsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTicketIdsResponse) ProtoMessage()    {}
func (*QueryTicketIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ec7651f31a90698, []int{3}
}

func (m *QueryTicketIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTicketIdsResponse.Unmarshal(m, b)
}
func (m *QueryTicketIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTicketIdsResponse.Marshal(b, m, deterministic)
}
func (m *QueryTicketIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTicketIdsResponse.Merge(m, src)
}
func (m *QueryTicketIdsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTicketIdsResponse.Size(m)
}
func (m *QueryTicketIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTicketIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTicketIdsResponse proto.InternalMessageInfo

func (m *QueryTicketIdsResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTicketsRequest)(nil), "openmatch.QueryTicketsRequest")
	proto.RegisterType((*QueryTicketsResponse)(nil), "openmatch.QueryTicketsResponse")
	proto.RegisterType((*QueryTicketIdsRequest)(nil), "openmatch.QueryTicketIdsRequest")
	proto.RegisterType((*QueryTicketIdsResponse)(nil), "openmatch.QueryTicketIdsResponse")
}

func init() { proto.RegisterFile("api/query.proto", fileDescriptor_5ec7651f31a90698) }

var fileDescriptor_5ec7651f31a90698 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x4e, 0x14, 0x3f,
	0x14, 0xc7, 0x33, 0xb3, 0x04, 0x42, 0xf9, 0xe5, 0x07, 0x56, 0x20, 0x64, 0x63, 0xb0, 0x0c, 0x31,
	0x81, 0xc5, 0x9d, 0x2e, 0x2b, 0x57, 0xab, 0x26, 0x20, 0x70, 0x41, 0xb2, 0xf8, 0x67, 0x31, 0x5e,
	0x78, 0xd7, 0xed, 0x1c, 0x67, 0x2b, 0xbb, 0x3d, 0xa5, 0xed, 0x80, 0x24, 0x5e, 0x19, 0x2f, 0xbd,
	0x92, 0x3b, 0x1f, 0xc1, 0x97, 0xf0, 0x21, 0x7c, 0x05, 0xe3, 0x73, 0x98, 0x99, 0x59, 0x64, 0x11,
	0x30, 0xf1, 0x6a, 0xa6, 0xe7, 0x7c, 0xcf, 0xf9, 0x7e, 0x7a, 0xda, 0x92, 0x69, 0x61, 0x14, 0x3f,
	0xca, 0xc0, 0x9e, 0xc6, 0xc6, 0xa2, 0x47, 0x3a, 0x89, 0x06, 0xf4, 0x40, 0x78, 0xd9, 0xab, 0xd2,
	0x3c, 0x37, 0x00, 0xe7, 0x44, 0x0a, 0xae, 0x4c, 0x57, 0xef, 0xa4, 0x88, 0x69, 0x1f, 0x78, 0x9e,
	0x12, 0x5a, 0xa3, 0x17, 0x5e, 0xa1, 0x3e, 0xcf, 0xde, 0x2f, 0x3e, 0xb2, 0x9e, 0x82, 0xae, 0xbb,
	0x13, 0x91, 0xa6, 0x60, 0x39, 0x9a, 0x42, 0x71, 0x55, 0x1d, 0xb5, 0xc8, 0xed, 0x17, 0xb9, 0xf3,
	0x4b, 0x25, 0x0f, 0xc1, 0xbb, 0x0e, 0x1c, 0x65, 0xe0, 0x3c, 0x5d, 0x26, 0x63, 0x06, 0xb1, 0xbf,
	0x10, 0xb0, 0x60, 0x65, 0xaa, 0x39, 0x1d, 0xff, 0x06, 0x8a, 0x9f, 0x23, 0xf6, 0x3b, 0x45, 0x32,
	0xda, 0x26, 0xb3, 0x97, 0x6b, 0x9d, 0x41, 0xed, 0x80, 0xae, 0x91, 0x09, 0x5f, 0x86, 0x16, 0x02,
	0x56, 0x59, 0x99, 0x6a, 0xde, 0x1a, 0xa9, 0x2f, 0xc5, 0x9d, 0x73, 0x45, 0xf4, 0x88, 0xcc, 0x8d,
	0x34, 0xd9, 0x4b, 0xfe, 0x0d, 0xa1, 0x46, 0xe6, 0xff, 0xac, 0x1e, 0x42, 0xcc, 0x90, 0x8a, 0x4a,
	0x4a, 0x80, 0xc9, 0x4e, 0xfe, 0xdb, 0x3c, 0x0b, 0xc9, 0x7f, 0x85, 0xf8, 0x00, 0xec, 0xb1, 0x92,
	0x40, 0xdf, 0x0f, 0xd7, 0x43, 0x7e, 0xba, 0x38, 0xe2, 0x71, 0xcd, 0x50, 0xaa, 0x77, 0x6f, 0xcc,
	0x97, 0x9e, 0xd1, 0xea, 0x87, 0xef, 0x3f, 0xce, 0xc2, 0xe5, 0x68, 0x91, 0x1f, 0xaf, 0x97, 0x07,
	0xea, 0x4a, 0x2b, 0x3e, 0xdc, 0x6d, 0xab, 0x08, 0xb6, 0x82, 0x5a, 0x23, 0xa0, 0x1f, 0x03, 0xf2,
	0xff, 0x65, 0x76, 0xca, 0xae, 0x37, 0xb8, 0x18, 0x4a, 0x75, 0xe9, 0x2f, 0x8a, 0x21, 0xc4, 0x5a,
	0x01, 0x71, 0x2f, 0x62, 0x37, 0x40, 0xa8, 0x64, 0x14, 0xe3, 0xc9, 0xa7, 0xca, 0xe7, 0xad, 0x9f,
	0x21, 0xfd, 0x16, 0x90, 0xb9, 0xfd, 0x7d, 0xd6, 0xc6, 0x54, 0x49, 0xb6, 0xb2, 0x23, 0xbc, 0x60,
	0x6d, 0x71, 0x0a, 0x76, 0x35, 0xda, 0x23, 0xe4, 0x99, 0x01, 0xcd, 0xf6, 0x73, 0x53, 0x3a, 0xdf,
	0xf3, 0xde, 0xb8, 0x16, 0xe7, 0x39, 0x47, 0xbd, 0x04, 0x49, 0xe0, 0xb8, 0xba, 0x7c, 0xb1, 0xae,
	0x27, 0xca, 0xc9, 0xcc, 0xb9, 0xcd, 0xf2, 0x9a, 0xa6, 0x16, 0x33, 0xe3, 0x62, 0x89, 0x83, 0xda,
	0x2b, 0x42, 0xb7, 0x8c, 0x90, 0x3d, 0x60, 0xcd, 0xb8, 0xc1, 0xda, 0x4a, 0x42, 0x7e, 0x52, 0x9b,
	0xe7, 0x2d, 0x53, 0xe5, 0x7b, 0x59, 0x37, 0x57, 0xf2, 0xb2, 0xf4, 0x0d, 0xda, 0x54, 0x0c, 0xc0,
	0x8d, 0x98, 0xf1, 0x6e, 0x1f, 0xbb, 0x7c, 0x20, 0x9c, 0x07, 0xcb, 0xdb, 0x7b, 0xdb, 0xbb, 0x4f,
	0x0f, 0x76, 0x9b, 0x95, 0xf5, 0xb8, 0x51, 0x0b, 0x83, 0xb0, 0x39, 0x23, 0x8c, 0xe9, 0x2b, 0x59,
	0xdc, 0x70, 0xfe, 0xd6, 0xa1, 0x6e, 0x5d, 0x89, 0x74, 0x1e, 0x92, 0xca, 0x46, 0x63, 0x83, 0x6e,
	0x90, 0x5a, 0x07, 0x7c, 0x66, 0x35, 0x24, 0xec, 0xa4, 0x07, 0x9a, 0xf9, 0x1e, 0x30, 0x0b, 0x0e,
	0x33, 0x2b, 0x81, 0x25, 0x08, 0x8e, 0x69, 0xf4, 0x0c, 0xde, 0x29, 0xe7, 0x63, 0x3a, 0x4e, 0xc6,
	0xbe, 0x84, 0xc1, 0x84, 0x7d, 0x4c, 0x16, 0x2e, 0x86, 0xc1, 0x76, 0x50, 0x66, 0x03, 0xd0, 0xe5,
	0x8b, 0xa2, 0x4b, 0xd7, 0x8f, 0x86, 0x3b, 0xe5, 0x81, 0x27, 0x28, 0x1d, 0x7f, 0x3d, 0xab, 0x5d,
	0x7d, 0x64, 0x2f, 0xe6, 0x30, 0xe5, 0xa6, 0xfb, 0x35, 0x9c, 0xcc, 0x7b, 0x16, 0x2d, 0xbb, 0xe3,
	0xc5, 0xb3, 0x7c, 0xf0, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x94, 0x5a, 0x5e, 0xf9, 0x14, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryServiceClient interface {
	// QueryTickets gets a list of Tickets that match all Filters of the input Pool.
	//   - If the Pool contains no Filters, QueryTickets will return all Tickets in the state storage.
	// QueryTickets pages the Tickets by `queryPageSize` and stream back responses.
	//   - queryPageSize is default to 1000 if not set, and has a minimum of 10 and maximum of 10000.
	QueryTickets(ctx context.Context, in *QueryTicketsRequest, opts ...grpc.CallOption) (QueryService_QueryTicketsClient, error)
	// QueryTicketIds gets the list of TicketIDs that meet all the filtering criteria requested by the pool.
	//   - If the Pool contains no Filters, QueryTicketIds will return all TicketIDs in the state storage.
	// QueryTicketIds pages the TicketIDs by `queryPageSize` and stream back responses.
	//   - queryPageSize is default to 1000 if not set, and has a minimum of 10 and maximum of 10000.
	QueryTicketIds(ctx context.Context, in *QueryTicketIdsRequest, opts ...grpc.CallOption) (QueryService_QueryTicketIdsClient, error)
}

type queryServiceClient struct {
	cc *grpc.ClientConn
}

func NewQueryServiceClient(cc *grpc.ClientConn) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) QueryTickets(ctx context.Context, in *QueryTicketsRequest, opts ...grpc.CallOption) (QueryService_QueryTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QueryService_serviceDesc.Streams[0], "/openmatch.QueryService/QueryTickets", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryServiceQueryTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueryService_QueryTicketsClient interface {
	Recv() (*QueryTicketsResponse, error)
	grpc.ClientStream
}

type queryServiceQueryTicketsClient struct {
	grpc.ClientStream
}

func (x *queryServiceQueryTicketsClient) Recv() (*QueryTicketsResponse, error) {
	m := new(QueryTicketsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryServiceClient) QueryTicketIds(ctx context.Context, in *QueryTicketIdsRequest, opts ...grpc.CallOption) (QueryService_QueryTicketIdsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QueryService_serviceDesc.Streams[1], "/openmatch.QueryService/QueryTicketIds", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryServiceQueryTicketIdsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueryService_QueryTicketIdsClient interface {
	Recv() (*QueryTicketIdsResponse, error)
	grpc.ClientStream
}

type queryServiceQueryTicketIdsClient struct {
	grpc.ClientStream
}

func (x *queryServiceQueryTicketIdsClient) Recv() (*QueryTicketIdsResponse, error) {
	m := new(QueryTicketIdsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QueryServiceServer is the server API for QueryService service.
type QueryServiceServer interface {
	// QueryTickets gets a list of Tickets that match all Filters of the input Pool.
	//   - If the Pool contains no Filters, QueryTickets will return all Tickets in the state storage.
	// QueryTickets pages the Tickets by `queryPageSize` and stream back responses.
	//   - queryPageSize is default to 1000 if not set, and has a minimum of 10 and maximum of 10000.
	QueryTickets(*QueryTicketsRequest, QueryService_QueryTicketsServer) error
	// QueryTicketIds gets the list of TicketIDs that meet all the filtering criteria requested by the pool.
	//   - If the Pool contains no Filters, QueryTicketIds will return all TicketIDs in the state storage.
	// QueryTicketIds pages the TicketIDs by `queryPageSize` and stream back responses.
	//   - queryPageSize is default to 1000 if not set, and has a minimum of 10 and maximum of 10000.
	QueryTicketIds(*QueryTicketIdsRequest, QueryService_QueryTicketIdsServer) error
}

// UnimplementedQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServiceServer struct {
}

func (*UnimplementedQueryServiceServer) QueryTickets(req *QueryTicketsRequest, srv QueryService_QueryTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryTickets not implemented")
}
func (*UnimplementedQueryServiceServer) QueryTicketIds(req *QueryTicketIdsRequest, srv QueryService_QueryTicketIdsServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryTicketIds not implemented")
}

func RegisterQueryServiceServer(s *grpc.Server, srv QueryServiceServer) {
	s.RegisterService(&_QueryService_serviceDesc, srv)
}

func _QueryService_QueryTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTicketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryTickets(m, &queryServiceQueryTicketsServer{stream})
}

type QueryService_QueryTicketsServer interface {
	Send(*QueryTicketsResponse) error
	grpc.ServerStream
}

type queryServiceQueryTicketsServer struct {
	grpc.ServerStream
}

func (x *queryServiceQueryTicketsServer) Send(m *QueryTicketsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _QueryService_QueryTicketIds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryTicketIdsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).QueryTicketIds(m, &queryServiceQueryTicketIdsServer{stream})
}

type QueryService_QueryTicketIdsServer interface {
	Send(*QueryTicketIdsResponse) error
	grpc.ServerStream
}

type queryServiceQueryTicketIdsServer struct {
	grpc.ServerStream
}

func (x *queryServiceQueryTicketIdsServer) Send(m *QueryTicketIdsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _QueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openmatch.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryTickets",
			Handler:       _QueryService_QueryTickets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryTicketIds",
			Handler:       _QueryService_QueryTicketIds_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/query.proto",
}
